### ISSUE TITLE
Wording and choices in Polls questions

### ISSUE THREAD

**Issue by jbrucker** [Nanokwok/ku-polls#13]
"coding language" should be "programming language".

And you don't have enough choices.  Top languages
include Typescript, Ruby, PHP, Go, and Rust.

All of your questions should have an "Other" choice.
I mentioned this in class.

**Comment by Nanokwok** [comment]
### Issue Closed: Update to Language Options

The issue regarding the language choices has been resolved. 

1. **Terminology Change**: The term "coding language" has been updated to "programming language" for better accuracy and clarity.

2. **Expanded Choices**: The list of top languages has been expanded to include Typescript, Ruby, PHP, Go, and Rust, addressing the initial limitation.

3. **Additional Option**: An "Other" choice has been added to all questions to accommodate any additional languages not listed.
